### ISSUE TITLE
TODO for final release

### ISSUE THREAD

**Issue by liamdugan** [rtx-on/rtx-explore#9]
### Stage 1
- [x] Implement subsurface scattering 
- [x] Fix normal mapping to be in tangent space
- [x] Add transmissive options to scene file and GUI
- [x] Add ability to remove objects from GUI (H)
- [x] Add ability to resize GUI window
- [x] Add global feature for switching between shlick and fresnel for glass materials
- [x] Hook in index of refraction to actually edit IOR
- [x] Create at least 5 different scenes, (have one be many glass objects, one with many metal objects, one with many transmissive objects, one with many emissive objects, one with combination of all types, (and of course one with sponza))
- [x] Rename the "Kewl RTX Image Comparison Thing"
- [x] Fix release to work with the gui (have the same options as debug)

## Stage 2
- [x] Remove commented out blocks of code and other unused parts of the codebase (Such as unused scene file elements, unused gui options, unused functions/variables to the best of our ability)
- [x] Update user guide and blog post with the added features (H)
- [x] Tweet some results to generate hype / gather gifs
- [x] Create more impressive renders of nice scenes through scene file
- [x] Get fps/frame render time performance data for GTX1070, 1080, and TITAN for at least 4 different scenes and different render depths (should be with default camera position)
- [x] Test stream compaction flags for performance data
- [x] Add finishing touches to README
- [x] Make final ppt and rehearse which scenes to demo
